/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/DANCE.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

 const DancingModel = (props) => {
  const group = React.useRef()
  const { nodes, materials, animations} = useGLTF('/DANCE.gltf')
  const {actions, names} = useAnimations(animations, group)
  console.log("names", names)
  React.useEffect(() => {
    actions[names[1]].reset().fadeIn(0.5).play()
    // actions[names[1]].reset().fadeIn(1.5).play()
    // actions[names[2]].reset().fadeIn(2.5).play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" rotation={[Math.PI / 1.8, 0, 0]} scale={0.4}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="dushka_2_kr_1_metal_0002" geometry={nodes.dushka_2_kr_1_metal_0002.geometry} material={materials['Material.032']} skeleton={nodes.dushka_2_kr_1_metal_0002.skeleton} />
          <skinnedMesh name="Object_15001_mesh_4002" geometry={nodes.Object_15001_mesh_4002.geometry} material={materials['Material.028']} skeleton={nodes.Object_15001_mesh_4002.skeleton} />
          <skinnedMesh name="Object_17002_Object_5001" geometry={nodes.Object_17002_Object_5001.geometry} material={materials['Material.023']} skeleton={nodes.Object_17002_Object_5001.skeleton} />
          <skinnedMesh name="Object_18001_Object_8001" geometry={nodes.Object_18001_Object_8001.geometry} material={materials['Material.022']} skeleton={nodes.Object_18001_Object_8001.skeleton} />
          <skinnedMesh name="Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb" geometry={nodes.Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb.geometry} material={materials['Material.027']} skeleton={nodes.Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb.skeleton} />
          <skinnedMesh name="Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4" geometry={nodes.Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4.geometry} material={materials['Material.026']} skeleton={nodes.Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4.skeleton} />
          <skinnedMesh name="Object_7002_Object_5001" geometry={nodes.Object_7002_Object_5001.geometry} material={materials['Material.030']} skeleton={nodes.Object_7002_Object_5001.skeleton} />
          <skinnedMesh name="Object_7005_Object_0001" geometry={nodes.Object_7005_Object_0001.geometry} material={materials['Material.033']} skeleton={nodes.Object_7005_Object_0001.skeleton} />
          <skinnedMesh name="Reebok_material0_0002" geometry={nodes.Reebok_material0_0002.geometry} material={materials['Material.025']} skeleton={nodes.Reebok_material0_0002.skeleton} />
          <skinnedMesh name="Reebok_material0_0003" geometry={nodes.Reebok_material0_0003.geometry} material={materials['Material.024']} skeleton={nodes.Reebok_material0_0003.skeleton} />
        </group>
      </group>
    </group>
  )
}
export default DancingModel

useGLTF.preload('/DANCE.gltf')
