/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/FLEX.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const FlexModel = (props) => {
  const group = React.useRef()
  const { nodes, materials, animations} = useGLTF('/FLEX.gltf')
  const {actions, names} = useAnimations(animations, group)
  console.log("names", names)
  React.useEffect(() => {
    actions[names[1]].reset().fadeIn(0.5).play()
    // actions[names[1]].reset().fadeIn(1.5).play()
    // actions[names[2]].reset().fadeIn(2.5).play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.306, 0, 0]} rotation={[Math.PI / 1.7, 0, 0]} scale={0.45}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="dushka_2_kr_1_metal_0001" geometry={nodes.dushka_2_kr_1_metal_0001.geometry} material={materials['Material.017']} skeleton={nodes.dushka_2_kr_1_metal_0001.skeleton} />
          <skinnedMesh name="Object_15001_mesh_4001" geometry={nodes.Object_15001_mesh_4001.geometry} material={materials['Material.016']} skeleton={nodes.Object_15001_mesh_4001.skeleton} />
          <skinnedMesh name="Object_17002_Object_5005" geometry={nodes.Object_17002_Object_5005.geometry} material={materials['Material.012']} skeleton={nodes.Object_17002_Object_5005.skeleton} />
          <skinnedMesh name="Object_18001_Object_8002" geometry={nodes.Object_18001_Object_8002.geometry} material={materials['Material.011']} skeleton={nodes.Object_18001_Object_8002.skeleton} />
          <skinnedMesh name="Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb3edb" geometry={nodes.Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb3edb.geometry} material={materials['Material.019']} skeleton={nodes.Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb3edb.skeleton} />
          <skinnedMesh name="Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4eb2b" geometry={nodes.Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4eb2b.geometry} material={materials['Material.018']} skeleton={nodes.Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4eb2b.skeleton} />
          <skinnedMesh name="Object_7002_Object_5004" geometry={nodes.Object_7002_Object_5004.geometry} material={materials['Material.021']} skeleton={nodes.Object_7002_Object_5004.skeleton} />
          <skinnedMesh name="Object_7005_Object_0003" geometry={nodes.Object_7005_Object_0003.geometry} material={materials['Material.020']} skeleton={nodes.Object_7005_Object_0003.skeleton} />
          <skinnedMesh name="Reebok_material0_0001" geometry={nodes.Reebok_material0_0001.geometry} material={materials['Material.013']} skeleton={nodes.Reebok_material0_0001.skeleton} />
          <skinnedMesh name="Reebok_material0_0004" geometry={nodes.Reebok_material0_0004.geometry} material={materials['Material.014']} skeleton={nodes.Reebok_material0_0004.skeleton} />
        </group>
      </group>
    </group>
  )
}
export default FlexModel
useGLTF.preload('/FLEX.gltf')
