/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/MAN_WAVING.gltf 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const ModelWaving = (props) => {
  const group = React.useRef()
  const { nodes, materials, animations} = useGLTF('/MAN_WAVING.gltf')
  const {actions, names} = useAnimations(animations, group)
  console.log("names", names)
  // const { scene } = useGLTF('/MAN_WAVING.gltf')
  // const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  // const { nodes, materials, animations } = useGraph(clone)
  // console.log("animations", animations)
  // const { actions, names } = useAnimations(animations, group)
  // console.log("names", names)
  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play()
    // actions[names[1]].reset().fadeIn(1.5).play()
    // actions[names[2]].reset().fadeIn(2.5).play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 1.8, 0, 0]} scale={0.4}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh castShadow name="dushka_2_kr_1_metal_0001" geometry={nodes.dushka_2_kr_1_metal_0001.geometry} material={materials['Material.041']} skeleton={nodes.dushka_2_kr_1_metal_0001.skeleton} />
          <skinnedMesh castShadow name="Object_15001_mesh_4001" geometry={nodes.Object_15001_mesh_4001.geometry} material={materials['Material.037']} skeleton={nodes.Object_15001_mesh_4001.skeleton} />
          <skinnedMesh castShadow name="Object_17002_Object_5005" geometry={nodes.Object_17002_Object_5005.geometry} material={materials['Material.031']} skeleton={nodes.Object_17002_Object_5005.skeleton} />
          <skinnedMesh castShadow name="Object_18001_Object_8002" geometry={nodes.Object_18001_Object_8002.geometry} material={materials['Material.029']} skeleton={nodes.Object_18001_Object_8002.skeleton} />
          <skinnedMesh castShadow name="Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb3edb" geometry={nodes.Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb3edb.geometry} material={materials['Material.034']} skeleton={nodes.Object_55002_BasiccharacterBody_BasiccharacterBodyD_7cb3edb.skeleton} />
          <skinnedMesh castShadow name="Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4eb2b" geometry={nodes.Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4eb2b.geometry} material={materials['Material.035']} skeleton={nodes.Object_55003_BasiccharacterBody_BasiccharacterBodyD_ad4eb2b.skeleton} />
          <skinnedMesh castShadow name="Object_7002_Object_5004" geometry={nodes.Object_7002_Object_5004.geometry} material={materials['Material.036']} skeleton={nodes.Object_7002_Object_5004.skeleton} />
          <skinnedMesh castShadow name="Object_7005_Object_0003" geometry={nodes.Object_7005_Object_0003.geometry} material={materials['Material.038']} skeleton={nodes.Object_7005_Object_0003.skeleton} />
          <skinnedMesh castShadow name="Reebok_material0_0001" geometry={nodes.Reebok_material0_0001.geometry} material={materials['Material.039']} skeleton={nodes.Reebok_material0_0001.skeleton} />
          <skinnedMesh castShadow name="Reebok_material0_0004" geometry={nodes.Reebok_material0_0004.geometry} material={materials['Material.040']} skeleton={nodes.Reebok_material0_0004.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default ModelWaving
useGLTF.preload('/MAN_WAVING.gltf')
